<?php
/**
 * Created by PhpStorm.
 * User: duanfuhao
 * Date: 2018/12/25
 * Time: 18:01
 * 帖子相关操作
 **/
namespace  App\HttpController\Utility;
use App\HttpController\Base;
use App\Lib\Upload\Image;

class UploadImage extends Base {

    public $imageObj = null;

    /**单图片文件上传接口**/
    public function upload() {
        try {
            $this->imageObj = new  Image($this->request());
            $data = $this->imageObj->upload();
            return $this->writeJson($data["code"],$data["msg"],$data["data"]);
        }catch (\Exception $e) {
            return $this->writeJson(400,'程序异常',$e->getMessage());
        }
    }

    /**多图片文件上传接口**/
    public function uploads() {
        try {
            $this->imageObj = new  Image($this->request());
            $data = $this->imageObj->uploads();
            return $this->writeJson($data["code"],$data["msg"],$data["data"]);
        }catch (\Exception $e) {
            return $this->writeJson(400,'程序异常',$e->getMessage());
        }
    }

    public function afterAction(?string $actionName): void
    {
        $this->imageObj = null;
        parent::afterAction($actionName); // TODO: Change the autogenerated stub
    }

}