<?php
/**
 * Created by PhpStorm.
 * User: duanfuhao
 * Date: 2019/1/9
 * Time: 15:31
 */

namespace App\HttpController\Admin;

use EasySwoole\Validate\Validate;
use App\Model\Admin\LoginModel;
use EasySwoole\Http\AbstractInterface\Controller;

class Login extends Controller
{

    public $loginObj = null;
    public $valitor = null;

    public function index()
    {

    }

    public function onRequest(?string $action): ?bool
    {
        if (!parent::onRequest($action)) {
            return false;
        }
        $this->valitor = new Validate();
        $this->loginObj = new LoginModel();
        return true;
    }

    /**登录接口 session入redis**/
    public function login()
    {
        try {
            $posts_array = $this->request()->getRequestParam();
            $comObj = new \App\HttpController\Utility\Commen();
            $posts_array = $comObj->purifierHtml($posts_array); //过滤html
            $posts_array = array_map(function ($val) { //过滤特殊字符
                if (!empty($val)) {
                    return htmlspecialchars($val);
                }
            }, $posts_array);
            if (!$this->checkPost($posts_array)) {
                return $this->writeJson(1, $this->valitor->getError()->__toString(), '');
            }
            $data = $this->loginObj->verifyAccout($posts_array);
            if (isset($data['code']) && $data['code'] == 0) {
                $sessionConfig = Config::getInstance()->getConf('session');
                $session_login_key = $sessionConfig['session_login_key'];
                $this->session(new \App\HttpController\Utility\RedisSession())->start();
                $this->session()->set($session_login_key, json_encode($data['data']), JSON_UNESCAPED_UNICODE);
            }
            return $this->writeJson($data['code'], $data['msg'], $data['data']);
        } catch (\Throwable $throwable) {
            return $this->writeJson(1, '程序异常:' . $throwable->getMessage(), '');
        }
    }

    /**退出登录**/
    public function loginOut()
    {
        $this->session(new \App\HttpController\Utility\RedisSession())->destroy();   //清除服务器session数据
        $this->response()->setCookie($this->session()->name(), '', time() - 1); //清除本地cookie记录
        $this->response()->redirect('/admin/login.html'); //跳转至登录页
        return false;
    }

    /**
     * @param $data
     * 添加帖子验证规则 dfh
     */
    public function checkPost($data)
    {
        $this->valitor->addColumn('account')->required('用户名不能为空')->betweenLen(1, 25, 'account需1-25字符之间');
        $this->valitor->addColumn('passwd')->required('密码不能为空')->betweenLen(1, 25, 'account需1-25字符之间');
        return $this->valitor->validate($data);
    }

    public function afterAction(?string $actionName): void
    {
        $this->valitor = null;
        $this->loginObj = null;
        parent::afterAction($actionName); // TODO: Change the autogenerated stub
    }
}