<?php
/**
 * Created by PhpStorm.
 * User: duanfuhao
 * Date: 2019/1/9
 * Time: 15:31
 */

namespace App\HttpController\Admin;

use App\HttpController\Base;
use EasySwoole\Validate\Validate;
use App\Model\Admin\LoginModel;

class Login extends Base
{

    public $loginObj = null;
    public $valitor = null;

    public function onRequest(?string $action): ?bool
    {
        parent::onRequest($action); // TODO: Change the autogenerated stub
        $this->valitor = new Validate();
        $this->loginObj = new LoginModel();
        return true;
    }

    public function login()
    {
        try {
            $posts_array = $this->request()->getRequestParam();
            $comObj = new \App\HttpController\Utility\Commen();
            $posts_array = $comObj->purifierHtml($posts_array); //过滤html
            $posts_array = array_map(function ($val) { //过滤特殊字符
                if (!empty($val)) {
                    return htmlspecialchars($val);
                }
            }, $posts_array);
            if (!$this->checkPost($posts_array)) {
                return $this->writeJson(1, $this->valitor->getError()->__toString(), '');
            }
            $data = $this->loginObj->verifyAccout($posts_array);
            return $this->writeJson($data['code'], $data['msg'], $data['data']);
        } catch (\Exception $e) {
            return $this->writeJson(1, '程序异常:' . $e->getMessage(), '');
        }
    }

    /**
     * @param $data
     * 添加帖子验证规则 dfh
     */
    public function checkPost($data)
    {
        $this->valitor->addColumn('account')->required('用户名不能为空')->betweenLen(1, 25, 'account需1-25字符之间');
        $this->valitor->addColumn('passwd')->required('密码不能为空')->betweenLen(1, 25, 'account需1-25字符之间');
        return $this->valitor->validate($data);
    }

    public function afterAction(?string $actionName): void
    {
        $this->valitor = null;
        $this->loginObj = null;
        parent::afterAction($actionName); // TODO: Change the autogenerated stub
    }
}