<?php
/**
 * Created by PhpStorm.
 * User: duanfuhao
 * Date: 2018/12/25
 * Time: 18:01
 * 帖子相关操作
**/
namespace  App\HttpController\Admin;
use App\HttpController\Base;
use App\Model\Admin\IndexModel;
use App\Lib\Upload\Image;

class Posts extends Base {

    public $imageObj = null;
    /**
     * 帖子列表页数据接口
     * Index constructor.
     */
    public function index() {
        $model = new IndexModel();
        $data = $model->index();
        return $this->writeJson($data["code"],$data["msg"],$data["data"]);
    }

    /**
     * 帖子添加页面数据接口
     */
    public function post_add() {
        $data = $this->request()->getRequestParam();
        return $this->writeJson(200,'ok',$data);
    }

    /**帖子编辑页面数据接口**/
    public function post_edit() {

    }

    public function afterAction(?string $actionName): void
    {
        $this->imageObj = null;
        parent::afterAction($actionName); // TODO: Change the autogenerated stub
    }

}