<?php
/**
 * Created by PhpStorm.
 * User: duanfuhao
 * Date: 2018/12/25
 * Time: 18:01
**/
namespace  App\HttpController\Admin;
use App\HttpController\Base;

class User extends Base {

    public function onRequest(?string $action): ?bool
    {
        if (!parent::onRequest($action)) {
            return false;
        }
        return parent::onRequest($action); // TODO: Change the autogenerated stub
    }

    /**
     * 获取用户信息
     * Index constructor.
     */
    public function index() {
        return $this->writeJson(0,'ok',$this->admin_info);
    }
}